/* ALOHA CHRISTMAS PHOTOBOOTH V2 */
const SUPABASE_URL = "https://lrajkpaqlrwtxuymmygz.supabase.co";
const SUPABASE_KEY = "sb_publishable_WlwmZmHDCL7brx5vadiHZQ_C0ay61KZ";
const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
const MAX_SHOTS = 10;

const $ = id => document.getElementById(id);
const camera=$('camera'), liveFrame=$('liveFrame'), modeScreen=$('modeScreen'), cameraScreen=$('cameraScreen'), reviewScreen=$('reviewScreen'), successScreen=$('successScreen');
const cameraMessage=$('cameraMessage'), cameraMessageText=$('cameraMessageText'), startCameraButton=$('startCameraButton'), switchCameraButton=$('switchCameraButton'), changeModeButton=$('changeModeButton');
const portraitModeButton=$('portraitModeButton'), landscapeModeButton=$('landscapeModeButton'), captureButton=$('captureButton'), flashButton=$('flashButton'), flashState=$('flashState');
const cameraTopControls=$('cameraTopControls'), cameraBottomControls=$('cameraBottomControls'), shotStatus=$('shotStatus'), shotCount=$('shotCount'), reviewButton=$('reviewButton');
const timerOffButton=$('timerOffButton'), timer3Button=$('timer3Button'), timer5Button=$('timer5Button'), countdownOverlay=$('countdownOverlay'), countdownNumber=$('countdownNumber');
const reviewGrid=$('reviewGrid'), selectedCount=$('selectedCount'), reviewHint=$('reviewHint'), takeMoreButton=$('takeMoreButton'), addSelectedButton=$('addSelectedButton');
const uploadStatus=$('uploadStatus'), uploadStatusText=$('uploadStatusText'), uploadError=$('uploadError'), reviewActions=$('reviewActions');
const successTitle=$('successTitle'), successMessage=$('successMessage'), successDownloads=$('successDownloads'), takeAnotherButton=$('takeAnotherButton');
const photoCanvas=$('photoCanvas'), ctx=photoCanvas.getContext('2d'), cameraContainer=document.querySelector('.camera-container');

let OUTPUT_WIDTH=1080, OUTPUT_HEIGHT=1920, photoMode='portrait', facingMode='user', currentStream=null, timerSeconds=0, countdownRunning=false, uploadRunning=false;
let capturedShots=[], lastUploadedShots=[], flashEnabled=false, stillFlashSupported=false;
const landscapeOrientation=window.matchMedia('(orientation: landscape)');

async function enterCameraFullscreen(){document.body.classList.add('camera-active');try{if(document.fullscreenEnabled&&!document.fullscreenElement){await document.documentElement.requestFullscreen({navigationUI:'hide'});}}catch(e){console.log('Fullscreen unavailable:',e);}}
async function exitCameraFullscreen(){document.body.classList.remove('camera-active');try{if(document.fullscreenElement)await document.exitFullscreen();}catch(e){console.log('Fullscreen exit unavailable:',e);}}

function switchToPortrait(){photoMode='portrait';OUTPUT_WIDTH=1080;OUTPUT_HEIGHT=1920;photoCanvas.width=OUTPUT_WIDTH;photoCanvas.height=OUTPUT_HEIGHT;liveFrame.src='frame.png';cameraContainer.classList.remove('landscape');cameraContainer.classList.add('portrait');updateModeButton();}
function switchToLandscape(){photoMode='landscape';OUTPUT_WIDTH=1920;OUTPUT_HEIGHT=1080;photoCanvas.width=OUTPUT_WIDTH;photoCanvas.height=OUTPUT_HEIGHT;liveFrame.src='frame_landscape.png';cameraContainer.classList.remove('portrait');cameraContainer.classList.add('landscape');updateModeButton();}
function syncPhotoModeWithDevice(){if(countdownRunning||uploadRunning)return;landscapeOrientation.matches?switchToLandscape():switchToPortrait();}
function changePhotoMode(){if(countdownRunning||uploadRunning)return;photoMode==='portrait'?switchToLandscape():switchToPortrait();}
function updateModeButton(){changeModeButton.textContent=photoMode==='portrait'?'🖼️':'📱';changeModeButton.title=photoMode==='portrait'?'Switch to Landscape':'Switch to Portrait';}
function selectPortraitMode(){switchToPortrait();modeScreen.classList.add('hidden');cameraScreen.classList.remove('hidden');prepareCameraScreen();}
function selectLandscapeMode(){switchToLandscape();modeScreen.classList.add('hidden');cameraScreen.classList.remove('hidden');prepareCameraScreen();}

function prepareCameraScreen(){stopCamera();captureButton.disabled=true;cameraTopControls.classList.add('hidden');cameraBottomControls.classList.add('hidden');shotStatus.classList.add('hidden');cameraMessage.classList.remove('hidden');cameraMessageText.textContent='Tap below to start the Aloha Christmas camera.';startCameraButton.classList.remove('hidden');}
async function getCameraStream(){currentStream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:facingMode}}});camera.srcObject=currentStream;await camera.play();updateCameraMirror();await updateFlashCapability();}
async function startCamera(){stopCamera();await enterCameraFullscreen();cameraMessage.classList.remove('hidden');cameraMessageText.textContent='Starting camera...';startCameraButton.classList.add('hidden');try{await getCameraStream();cameraMessage.classList.add('hidden');cameraTopControls.classList.remove('hidden');cameraBottomControls.classList.remove('hidden');shotStatus.classList.remove('hidden');captureButton.disabled=false;updateShotStatus();}catch(error){console.error(error);await exitCameraFullscreen();cameraMessageText.textContent='The camera could not be started. Please check camera permission and try again.';startCameraButton.classList.remove('hidden');}}
function stopCamera(){if(currentStream){currentStream.getTracks().forEach(track=>track.stop());}camera.srcObject=null;currentStream=null;flashEnabled=false;stillFlashSupported=false;updateFlashButton();}
async function switchCamera(){if(countdownRunning)return;facingMode=facingMode==='user'?'environment':'user';stopCamera();cameraMessage.classList.remove('hidden');cameraMessageText.textContent='Switching camera...';try{await getCameraStream();cameraMessage.classList.add('hidden');cameraTopControls.classList.remove('hidden');cameraBottomControls.classList.remove('hidden');shotStatus.classList.remove('hidden');captureButton.disabled=false;}catch(error){console.error(error);cameraMessageText.textContent='Could not switch camera. Please try again.';startCameraButton.classList.remove('hidden');}}
function updateCameraMirror(){camera.classList.toggle('selfie',facingMode==='user');}

async function updateFlashCapability(){stillFlashSupported=false;flashEnabled=false;if(facingMode!=='environment'||!currentStream||typeof ImageCapture==='undefined'){updateFlashButton();return;}try{const track=currentStream.getVideoTracks()[0];const ic=new ImageCapture(track);if(typeof ic.getPhotoCapabilities==='function'){const caps=await ic.getPhotoCapabilities();const modes=Array.isArray(caps.fillLightMode)?caps.fillLightMode:[];stillFlashSupported=modes.includes('flash');}}catch(e){console.log('Still flash capability unavailable:',e);}updateFlashButton();}
function updateFlashButton(){flashButton.classList.toggle('hidden',!stillFlashSupported);flashButton.classList.toggle('active',flashEnabled&&stillFlashSupported);flashState.textContent=flashEnabled?'ON':'OFF';flashButton.title=flashEnabled?'Still flash on':'Still flash off';}
function toggleFlash(){if(!stillFlashSupported)return;flashEnabled=!flashEnabled;updateFlashButton();}

function setTimer(seconds){if(countdownRunning)return;timerSeconds=seconds;[timerOffButton,timer3Button,timer5Button].forEach(b=>b.classList.remove('active'));(seconds===0?timerOffButton:seconds===3?timer3Button:timer5Button).classList.add('active');}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function setCameraControlsDisabled(disabled){[captureButton,timerOffButton,timer3Button,timer5Button,changeModeButton,switchCameraButton,flashButton,reviewButton].forEach(b=>b.disabled=disabled);}
async function runCountdown(){if(countdownRunning||!currentStream||capturedShots.length>=MAX_SHOTS)return;if(timerSeconds===0){await capturePhoto();return;}countdownRunning=true;setCameraControlsDisabled(true);countdownOverlay.classList.remove('hidden');try{for(let n=timerSeconds;n>0;n--){countdownNumber.textContent=n;await wait(1000);}countdownOverlay.classList.add('hidden');await capturePhoto();}finally{countdownRunning=false;countdownOverlay.classList.add('hidden');countdownNumber.textContent='';setCameraControlsDisabled(false);captureButton.disabled=capturedShots.length>=MAX_SHOTS;reviewButton.disabled=capturedShots.length===0;}}

function drawSourceCover(source,sw,sh){const srcRatio=sw/sh,dstRatio=OUTPUT_WIDTH/OUTPUT_HEIGHT;let sx=0,sy=0,sWidth=sw,sHeight=sh;if(srcRatio>dstRatio){sWidth=sh*dstRatio;sx=(sw-sWidth)/2;}else{sHeight=sw/dstRatio;sy=(sh-sHeight)/2;}ctx.drawImage(source,sx,sy,sWidth,sHeight,0,0,OUTPUT_WIDTH,OUTPUT_HEIGHT);}
function drawVideoClean(){ctx.clearRect(0,0,OUTPUT_WIDTH,OUTPUT_HEIGHT);if(facingMode==='user'){ctx.save();ctx.translate(OUTPUT_WIDTH,0);ctx.scale(-1,1);drawSourceCover(camera,camera.videoWidth,camera.videoHeight);ctx.restore();}else{drawSourceCover(camera,camera.videoWidth,camera.videoHeight);}}
function canvasToBlob(){return new Promise(resolve=>photoCanvas.toBlob(resolve,'image/jpeg',0.92));}
function waitForFrame(){return new Promise((resolve,reject)=>{if(liveFrame.complete&&liveFrame.naturalWidth>0){resolve();return;}const ok=()=>{cleanup();resolve();},bad=()=>{cleanup();reject(new Error('Frame could not be loaded.'));},cleanup=()=>{liveFrame.removeEventListener('load',ok);liveFrame.removeEventListener('error',bad);};liveFrame.addEventListener('load',ok);liveFrame.addEventListener('error',bad);});}
async function drawStillCleanIfAvailable(){if(facingMode!=='environment'||typeof ImageCapture==='undefined'||!currentStream){drawVideoClean();return;}try{const track=currentStream.getVideoTracks()[0];const ic=new ImageCapture(track);const blob=await ic.takePhoto({fillLightMode:flashEnabled&&stillFlashSupported?'flash':'off'});const bitmap=await createImageBitmap(blob);ctx.clearRect(0,0,OUTPUT_WIDTH,OUTPUT_HEIGHT);drawSourceCover(bitmap,bitmap.width,bitmap.height);bitmap.close();}catch(e){console.log('Still capture fallback:',e);drawVideoClean();}}

function createCaptureId(){const rand=(crypto.randomUUID?crypto.randomUUID().replaceAll('-',''):Date.now().toString(36)+Math.random().toString(36).slice(2)).slice(0,12).toUpperCase();return 'AC26_'+rand;}
async function capturePhoto(){if(!camera.videoWidth||!camera.videoHeight)return;captureButton.disabled=true;try{await waitForFrame();await drawStillCleanIfAvailable();const cleanBlob=await canvasToBlob();ctx.drawImage(liveFrame,0,0,OUTPUT_WIDTH,OUTPUT_HEIGHT);const framedBlob=await canvasToBlob();if(!cleanBlob||!framedBlob)throw new Error('Could not create photo.');const shot={id:createCaptureId(),cleanBlob,framedBlob,mode:photoMode,selected:true};capturedShots.push(shot);attemptCleanDownload(shot);updateShotStatus();flashCaptureEffect();if(capturedShots.length>=MAX_SHOTS){await openReview();}}catch(e){console.error(e);alert('Photo error:\n\n'+e.message);}finally{captureButton.disabled=capturedShots.length>=MAX_SHOTS;}}
function flashCaptureEffect(){cameraContainer.animate([{filter:'brightness(1)'},{filter:'brightness(1.7)'},{filter:'brightness(1)'}],{duration:180});}
function updateShotStatus(){shotCount.textContent=`${capturedShots.length} / ${MAX_SHOTS}`;reviewButton.disabled=capturedShots.length===0;}

async function openReview(){if(!capturedShots.length)return;stopCamera();cameraTopControls.classList.add('hidden');cameraBottomControls.classList.add('hidden');shotStatus.classList.add('hidden');await exitCameraFullscreen();cameraScreen.classList.add('hidden');reviewScreen.classList.remove('hidden');renderReview();}
function renderReview(){reviewGrid.innerHTML='';capturedShots.forEach((shot,index)=>{const btn=document.createElement('button');btn.type='button';btn.className=`review-shot ${shot.mode==='landscape'?'landscape':''} ${shot.selected?'selected':''}`;const img=document.createElement('img');img.src=URL.createObjectURL(shot.framedBlob);img.onload=()=>URL.revokeObjectURL(img.src);const check=document.createElement('span');check.className='review-check';check.textContent=shot.selected?'✓':'○';btn.append(img,check);btn.addEventListener('click',()=>{shot.selected=!shot.selected;renderReview();});reviewGrid.appendChild(btn);});const count=capturedShots.filter(s=>s.selected).length;selectedCount.textContent=`${count} selected`;reviewHint.textContent=count?'Only selected photos will be added to the party.':'Select at least one photo.';addSelectedButton.disabled=count===0||uploadRunning;takeMoreButton.disabled=uploadRunning||capturedShots.length>=MAX_SHOTS;addSelectedButton.textContent=count?`☁️ Add ${count} Selected to Party`:'☁️ Add Selected to Party';}
async function takeMorePhotos(){reviewScreen.classList.add('hidden');cameraScreen.classList.remove('hidden');await startCamera();}

async function uploadShot(shot){const cleanPath=`clean/${shot.id}_clean.jpg`,framedPath=`framed/${shot.id}_framed.jpg`;let r=await supabaseClient.storage.from('party-photos').upload(cleanPath,shot.cleanBlob,{contentType:'image/jpeg',cacheControl:'3600',upsert:false});if(r.error)throw r.error;r=await supabaseClient.storage.from('party-photos').upload(framedPath,shot.framedBlob,{contentType:'image/jpeg',cacheControl:'3600',upsert:false});if(r.error)throw r.error;r=await supabaseClient.from('party_photos').insert({capture_id:shot.id,clean_path:cleanPath,framed_path:framedPath,photo_mode:shot.mode,status:'pending'});if(r.error)throw r.error;}
async function addSelectedToParty(){if(uploadRunning)return;const selected=capturedShots.filter(s=>s.selected);if(!selected.length)return;uploadRunning=true;reviewActions.classList.add('hidden');uploadError.classList.add('hidden');uploadStatus.classList.remove('hidden');try{for(let i=0;i<selected.length;i++){uploadStatusText.textContent=`Uploading photo ${i+1} of ${selected.length}...`;await uploadShot(selected[i]);}lastUploadedShots=selected;uploadRunning=false;showSuccessScreen();}catch(e){console.error(e);uploadRunning=false;uploadStatus.classList.add('hidden');reviewActions.classList.remove('hidden');uploadError.classList.remove('hidden');uploadError.textContent='Upload failed. '+e.message+' Please try again.';renderReview();}}

function attemptCleanDownload(shot){try{downloadBlob(shot.cleanBlob,`${shot.id}_clean.jpg`);}catch(e){console.log('Automatic clean download was blocked:',e);}}
function downloadBlob(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function showSuccessScreen(){uploadStatus.classList.add('hidden');reviewScreen.classList.add('hidden');successScreen.classList.remove('hidden');successTitle.textContent=`🎄 ${lastUploadedShots.length} ${lastUploadedShots.length===1?'photo':'photos'} joined the party!`;successMessage.textContent='Clean photos were automatically offered for saving. Use the buttons below if your browser blocked any download.';successDownloads.innerHTML='';lastUploadedShots.forEach((shot,index)=>{const card=document.createElement('div');card.className='download-card';const img=document.createElement('img');img.src=URL.createObjectURL(shot.framedBlob);img.onload=()=>URL.revokeObjectURL(img.src);const info=document.createElement('div');info.className='download-info';const title=document.createElement('strong');title.textContent=`Photo ${index+1}`;const clean=document.createElement('button');clean.type='button';clean.textContent='🖼️ Save Clean';clean.onclick=()=>downloadBlob(shot.cleanBlob,`${shot.id}_clean.jpg`);const framed=document.createElement('button');framed.type='button';framed.textContent='📸 Save Framed';framed.onclick=()=>downloadBlob(shot.framedBlob,`${shot.id}_framed.jpg`);info.append(title,clean,document.createTextNode(' '),framed);card.append(img,info);successDownloads.appendChild(card);});}
async function takeAnotherSet(){successScreen.classList.add('hidden');capturedShots=[];lastUploadedShots=[];uploadRunning=false;syncPhotoModeWithDevice();cameraScreen.classList.remove('hidden');await startCamera();}

portraitModeButton.addEventListener('click',selectPortraitMode);landscapeModeButton.addEventListener('click',selectLandscapeMode);changeModeButton.addEventListener('click',changePhotoMode);startCameraButton.addEventListener('click',startCamera);switchCameraButton.addEventListener('click',switchCamera);flashButton.addEventListener('click',toggleFlash);captureButton.addEventListener('click',runCountdown);reviewButton.addEventListener('click',openReview);takeMoreButton.addEventListener('click',takeMorePhotos);addSelectedButton.addEventListener('click',addSelectedToParty);takeAnotherButton.addEventListener('click',takeAnotherSet);timerOffButton.onclick=()=>setTimer(0);timer3Button.onclick=()=>setTimer(3);timer5Button.onclick=()=>setTimer(5);
landscapeOrientation.addEventListener('change',syncPhotoModeWithDevice);window.addEventListener('resize',syncPhotoModeWithDevice);window.addEventListener('pagehide',stopCamera);
syncPhotoModeWithDevice();updateModeButton();setTimer(0);updateShotStatus();updateFlashButton();
